# Generated by Django 5.2.8 on 2025-11-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0003_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
