# Generated by Django 5.2.8 on 2025-11-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0010_alter_notification_options_alter_notification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
