# Generated by Django 5.2.8 on 2025-11-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0012_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
