# Generated by Django 5.2.8 on 2025-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0014_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
