# Generated by Django 5.2.8 on 2025-12-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0018_remove_cart_added_at_orderpayment_total_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='No address'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MobileOTP',
        ),
    ]
