# Generated by Django 5.2.8 on 2025-12-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buykoapp', '0021_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
