"""
Django settings for buykopro project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d83glr0ao45smpk-k4c=o03yl+7z43#+$voyh$z@0q$lm#p)0('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'buykoapp',
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'buykopro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # or your templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # required for admin and auth
                'django.template.context_processors.debug',
                'django.template.context_processors.request',       # <-- add this
                'django.contrib.auth.context_processors.auth',      # <-- add this
                'django.contrib.messages.context_processors.messages',
                'buykoapp.context_processors.cart_count',

                  # <-- add this
            ],
        },
    },
]



WSGI_APPLICATION = 'buykopro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api

# -------- DATABASE (PostgreSQL) --------
DATABASES = {
    'default': dj_database_url.parse(
        'postgresql://buyko_user:A2mxy2iIKmZdK43kzTlAlnYxjEF4MgpX@dpg-d78ftk450q8c73esu3i0-a.oregon-postgres.render.com/buyko'
    )
}

# -------- CLOUDINARY CONFIG --------
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dprmswawl',
    'API_KEY': '214959546412619',
    'API_SECRET': '0hqauc8yw-Vc11eJktNSIBUT5GI'
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'dilshadklr04@gmail.com'
EMAIL_HOST_PASSWORD = 'rbhl jtpp zekg hhbf'   # Gmail App Password
DEFAULT_FROM_EMAIL = 'Buyko <dilshadklr04@gmail.com>'



# settings.py
import os

RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "rzp_test_RmboxNgTbFao5A")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET", "bMwCYlMIm7lVt0NU5raH5xND")


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"